services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8001:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on:
      - php
      - mysql

  php:
    build:
      context: docker/dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - "./db_data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

  composer:
    build: 
      context: docker/dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - "./src:/var/www/laravel"

  artisan:
    build:
      context: docker/dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - "./src:/var/www/laravel"
    entrypoint: ["php", "/var/www/laravel/artisan"]

  worker:
    build:
      context: docker/dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    command: php /var/www/laravel/artisan queue:work
    depends_on:
      - mysql
      - php

  schedule:
    build:
      context: docker/dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    command: >
      sh -c "while true; do php /var/www/laravel/artisan schedule:run; sleep 60; done"
    depends_on:
      - php
      - mysql

